source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'EZTamperDetection_Example', :exclusive => true do
  pod 'EZTamperDetection', :path => '../'
end

target 'EZTamperDetection_Tests', :exclusive => true do
  pod 'EZTamperDetection', :path => '../'

  
end
